server:
  port: 9022
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
      url: jdbc:mysql://120.55.42.127:3306/storage_nv_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: storage_nv_dev
      password: storage_nv_dev2022$%^321
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        max-active: 200
        max-wait: 30000
        initial-size: 5
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
        requestInterceptors:
          - com.tiCloudServer.systemContact.controller.interceptor.HttpInterceptor
#        encoder: com.example.SimpleEncoder
#        decoder: com.example.SimpleDecoder

mybatis:
  table:
    auto: add
    #create        系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
    #update        系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
    #none         系统不做任何处理。
    #add        新增表/新增字段/新增索引/新增唯一约束的功能，不做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
  model:
    pack: com.tiCloudServer.systemContact.entity #扫描用于创建表的对象的包名，多个包用“,”隔开
  database:
    type: mysql #数据库类型 目前只支持mysql
